<?= $this->doctype(); ?>
<html>
<head>
    <?= $this->headMeta()->setCharset('UTF-8'); ?>
    <?=
    $this->HeadLink()
        ->appendStylesheet('/vendor/bootstrap3/css/bootstrap.min.css'); ?>

    <?=
    $this->HeadScript()
        ->appendFile('/vendor/jquery/jquery/jquery.min.js')
        ->appendFile('/vendor/bootstrap3/js/bootstrap.min.js')->appendFile('/vendor/bootstrap3/js/3.min.js');
    ?>
</head>

<body>

<div class="container">

    <?=
    $this->navigation()
        ->menu()
        ->renderPartial('jz-cms-admin-navigation-factory','jz-cms-admin-navigation');
    ?>

    <div class="col-sm-12">
        <?=$this->navigation()
            ->breadcrumbs()
            ->renderPartial('jz-cms-admin-navigation-factory','jz-cms-admin-breadcrumnbs');?>

        <?= $this->content; ?>
    </div>
</div>



</body>

</html>