<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#jz-cms-admin-navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">JzCMS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="kp-cms-admin-navigation">
        <ul class="nav navbar-nav">

            <?php foreach ($container as $page):?>
                <?php /* @var $page \Zend\Navigation\Page\Uri */ ?>
                <li class="dropdown <?= !$page->isActive(true)?:'active';?>">
                    <a href="<?=$page->getHref();?>" class="dropdown-toggle" data-toggle="dropdown">
                        <?=$page->getLabel(); ?> <b class="caret"></b>
                    </a>
                    <?php if ($page->hasPages()): ?>
                        <ul class="dropdown-menu">
                            <?php foreach ($page->getPages() as $childPage): ?>
                                <?php /* @var $childPage \Zend\Navigation\Page\Mvc */ ?>
                                <li class="<?= !$childPage->isActive(true)?:'active';?>">
                                    <a href="<?= $childPage->getHref(); ?>">
                                        <?= $childPage->getLabel(); ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>

    </div>
</nav>



